# -*- coding: utf-8 -*-
"""Beta_VAE_Anomaly_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSst6Sczrs3lDHVB6PB_VjkCzmCM9fjR

# Beta-VAE Anomaly Detector

Loss Func: SSIM + Beta * (KL Divergence)

Beta-Variational: Encoder outputs a mean and a log variance. A vector is sampled from gaussian noise, and said vector is scaled and shifted by the mean and std from the encoder. This vector is the latent vector we pass our Decoder.

A hyper parameter beta is added to scale how much the KL divergence affects the loss function
"""

# Download the dataset, setup packages
# SSIM download
!pip install torchmetrics
import os
import cv2
import numpy as np
import numpy.typing as npt
import matplotlib.pyplot as plt
import random
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score

import torch as torch
import torch.nn as nn
import torch.optim as optim

# SSIM addition
from torchmetrics.image import StructuralSimilarityIndexMeasure

if not os.path.exists('dataset.zip'):
  !gdown 1_pRKXtYRjWjY0seYqyx25nOxjtr-mHYg
  !unzip -q -u dataset.zip
else:
  print('Already downloaded')

# Helper function to load in data set
def load_dataset(class_name = 'pasta'):
  assert class_name in ['pasta', 'screws', 'capsule']
  dir = './dataset/'+class_name+'/'
  training_images = []
  testing_images = []
  testing_labels = []
  for file_name in os.listdir(dir+'train/good/'):
    training_images.append(cv2.cvtColor(cv2.imread(dir+'train/good/'+file_name), cv2.COLOR_BGR2RGB))
  for file_name in os.listdir(dir+'test/good/'):
    testing_images.append(cv2.cvtColor(cv2.imread(dir+'test/good/'+file_name), cv2.COLOR_BGR2RGB))
    testing_labels.append(0)
  for file_name in os.listdir(dir+'test/bad/'):
    testing_images.append(cv2.cvtColor(cv2.imread(dir+'test/bad/'+file_name), cv2.COLOR_BGR2RGB))
    testing_labels.append(1)

  # returns a normalized (0-1) numpy array of size (n,)
  return np.array(training_images)/255., np.array(testing_images)/255., np.array(testing_labels)

def basic_evaluation(predictions : np.ndarray, targets : np.ndarray):
  print(targets)
  print(predictions)
  print('Accuracy Score: ', accuracy_score(targets, predictions>0.5))
  print('F1 Score: ', f1_score(targets, predictions>0.5))
  print('AUROC Score:', roc_auc_score(targets, predictions))

# Written by AI
# Sets the weight initialization seed so it is the same every time
def set_seed(seed=77):
    """Locks down all random number generators for reproducibility."""
    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Call this immediately!
set_seed(2222)

class VAE_Encoder(nn.Module):
    def __init__(self, image_height, image_width, latent_vector_dim = 16):
        super().__init__()

        # CNN network
        self.convolution = nn.Sequential(

            nn.Conv2d(3, 32, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(32, affine = True),

            nn.Conv2d(32, 64, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(64, affine = True),

            nn.Conv2d(64, 128, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(128, affine = True),

            nn.Conv2d(128, 256, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(256, affine = True),
        )

        # Dummy pass to get flattened_size and spatial_size
        dummy_input = torch.zeros(1, 3, image_height, image_width)
        dummy_output = self.convolution(dummy_input)

        self.flattened_size = dummy_output.view(1, -1).size(1)
        self.spatial_shape = dummy_output.shape[1:]

        self.fully_connected_mu = nn.Linear(self.flattened_size, latent_vector_dim)
        self.fully_connected_log_var = nn.Linear(self.flattened_size, latent_vector_dim)

    def forward(self,x):

        # Go through our convolutional layers
        z = self.convolution(x)

        # flatten output into latent vector
        x = torch.flatten(z, start_dim =1)

        # now we want our flattened vector to pass through both fc layers to yeild 2 parameters which will act as our mean and variance
        mu = self.fully_connected_mu(x)
        log_var = self.fully_connected_log_var(x)

        return mu, log_var

def reparametrization(mu, log_var):

      # std = sqrt(variance)
      var = torch.exp(log_var)
      std = torch.sqrt(var)

      # torch.randn_like returns a tensor with same size as input of a random value from a gaussian distribution with mean 0 and std 1
      # inputting in std as want to have same shape
      eps = torch.randn_like(std)

      # scale and shift are gaussian by the mu and std
      # z = mean + (random noise * standard deviation)
      z = mu + (eps *std)

      return z

class VAE_Decoder(nn.Module):
    def __init__(self, latent_vector_dim, flattened_size, spatial_shape):
        super().__init__()
        self.spatial_shape = spatial_shape

        self.fully_connected_decoder_in = nn.Linear(latent_vector_dim, flattened_size)

        # decoder mirrors encoder and reverses to reconstruct the spacial resolution
        self.decoder = nn.Sequential(
            nn.Unflatten(1, self.spatial_shape),

            nn.ConvTranspose2d(256, 128, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(128, affine = True),

            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(64, affine = True),

            nn.ConvTranspose2d(64, 32, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.InstanceNorm2d(32, affine = True),

            nn.ConvTranspose2d(32, 3, 4, stride=2, padding=1),
            nn.Sigmoid()
        )


    def forward(self, z):

        # expand the latent vector into an input big enough for our decoder
        x = self.fully_connected_decoder_in(z)
        output = self.decoder(x)

        return output

def VAE_loss(x, recon_out, mu, log_var, ssim_metric, beta = 0.25):

  # Reconstruction loss (SSIM)
  ssim_score = ssim_metric(recon_out, x)

  # A perfect reconstruction gives SSIM = 1 . Therefore to make this a loss function we do 1-1.
  reconstruction_loss = 1.0 - ssim_score

  # KL loss
  kl_divergence = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp(), dim=1)
  kl_loss = torch.mean(kl_divergence)

  return reconstruction_loss + (beta*kl_loss)

# Full Encoder and Decoder
class VAE(nn.Module):
  def __init__(self, image_height, image_width, latent_vector_dim = 16, num_epochs=30):
    super().__init__()

    self.encoder = VAE_Encoder(image_height, image_width)

    self.decoder = VAE_Decoder(latent_vector_dim, self.encoder.flattened_size, self.encoder.spatial_shape)

  def forward(self, x):

    mu, logvar = self.encoder(x)

    z = reparametrization(mu, logvar)

    reconstructed_output = self.decoder(z)

    return reconstructed_output, mu, logvar

# Made with AI
# Outputs the input images and corresponding reconstructed images
def visualize_reconstructions(model, test_data, num_images=5):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    indices = np.random.choice(len(test_data), num_images, replace=False)
    sample_images = test_data[indices]

    x = torch.tensor(sample_images).permute(0, 3, 1, 2).float().to(device)

    with torch.no_grad():
        # Fix: our model outputs 3 values
        reconstructed = model(x)[0]

    # Move back to CPU and format for matplotlib (N, H, W, C)
    recon_images = reconstructed.permute(0, 2, 3, 1).cpu().numpy()

    # Plotting
    fig, axes = plt.subplots(num_images, 2, figsize=(6, 3 * num_images))
    fig.suptitle("Original vs Reconstructed", fontsize=16)

    for i in range(num_images):
        # Original Image
        axes[i, 0].imshow(sample_images[i])
        axes[i, 0].set_title("Original")
        axes[i, 0].axis('off')

        # Reconstructed Image
        axes[i, 1].imshow(recon_images[i])
        axes[i, 1].set_title("Reconstructed")
        axes[i, 1].axis('off')

    plt.tight_layout()
    plt.show()

def train_model(model, dataset, num_epochs, learning_rate=1e-4, beta=0.25):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)

    # SSIM init ((our image values are 0 to 1))
    ssim_metric = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)

    # convert numpy to torch
    x = torch.tensor(dataset).permute(0,3,1,2).float().to(device)

    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    for epoch in range(num_epochs):

      model.train()

      # compute vae forward
      recon_out, mu, logvar = model(x)

      # compute loss
      loss = VAE_loss(x, recon_out, mu, logvar, ssim_metric, beta)

      # clear old gradients from last iter
      optimizer.zero_grad()

      # backward pass for optimization
      loss.backward()

      # update
      optimizer.step()

      print("epoch",epoch,"loss",loss.item())


def predict(model, test_data):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    # Initialize SSIM with reduction='none' to get individual scores per image
    ssim_metric = StructuralSimilarityIndexMeasure(data_range=1.0, reduction='none').to(device)

    x = torch.tensor(test_data).permute(0,3,1,2).float().to(device)

    with torch.no_grad():
        x_hat = model(x)[0]

        # Calculate SSIM for each image
        # (1.0 means perfect match, 0.0 means no match)
        ssim_scores = ssim_metric(x_hat, x)

        # Convert SSIM to an "error" or "anomaly" score (higher = more anomalous)
        errors = 1.0 - ssim_scores

    return errors.cpu().numpy()

def do_analysis(class_name):
  training_images, testing_images, testing_labels = load_dataset(class_name=class_name)

  img_height = training_images.shape[1]
  img_width = training_images.shape[2]

  vae_model = VAE(img_height, img_width)

  train_model(vae_model, training_images, num_epochs=30, beta = 0.25)

  predictions = predict(vae_model, testing_images)
  basic_evaluation(predictions, testing_labels)

  print(f"\nVisualizing sample reconstructions for {class_name}...")
  visualize_reconstructions(vae_model, testing_images, num_images=4)

print("screws analysis")
do_analysis('screws')
print("pasta analysis")
do_analysis('pasta')
print("capsule analysis")
do_analysis('capsule')