# -*- coding: utf-8 -*-
"""VAE_Anomaly_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1z4WZAEtTZAB9vB4i_pxZVK9SXvb-19

# VAE Anomaly Detector

Loss Fun: SSIM + KL Divergence

Variational: Encoder outputs a mean and a log variance. A vector is sampled from gaussian noise, and said vector is scaled and shifted by the mean and std from the encoder. This vector is the latent vector we pass our Decoder.
"""

# Download the dataset, setup packages
# SSIM download
!pip install torchmetrics
import os
import cv2
import numpy as np
import numpy.typing as npt
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, roc_auc_score
import random

# SSIM addition
from torchmetrics.image import StructuralSimilarityIndexMeasure

import torch as torch
import torch.nn as nn
import torch.optim as optim

if not os.path.exists('dataset.zip'):
  !gdown 1_pRKXtYRjWjY0seYqyx25nOxjtr-mHYg
  !unzip -q -u dataset.zip
else:
  print('Already downloaded')

# Helper function to load in data set
def load_dataset(class_name = 'pasta'):
  assert class_name in ['pasta', 'screws', 'capsule']
  dir = './dataset/'+class_name+'/'
  training_images = []
  testing_images = []
  testing_labels = []
  for file_name in os.listdir(dir+'train/good/'):
    training_images.append(cv2.cvtColor(cv2.imread(dir+'train/good/'+file_name), cv2.COLOR_BGR2RGB))
  for file_name in os.listdir(dir+'test/good/'):
    testing_images.append(cv2.cvtColor(cv2.imread(dir+'test/good/'+file_name), cv2.COLOR_BGR2RGB))
    testing_labels.append(0)
  for file_name in os.listdir(dir+'test/bad/'):
    testing_images.append(cv2.cvtColor(cv2.imread(dir+'test/bad/'+file_name), cv2.COLOR_BGR2RGB))
    testing_labels.append(1)

  # returns a normalized (0-1) numpy array of size (n,)
  return np.array(training_images)/255., np.array(testing_images)/255., np.array(testing_labels)

def basic_evaluation(predictions : np.ndarray, targets : np.ndarray):
  print(targets)
  print(predictions)
  print('AUROC Score:', roc_auc_score(targets, predictions))

# Written by AI
# Sets the weight initialization seed so it is the same every time
def set_seed(seed=77):
    """Locks down all random number generators for reproducibility."""
    # 1. Python built-in random module
    random.seed(seed)

    # 2. NumPy (This fixes your np.random.choice issue!)
    np.random.seed(seed)

    # 3. PyTorch (CPU and GPU)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    # 4. CuDNN (GPU backend)
    # Note: Forcing deterministic behavior can slightly slow down training
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Call this immediately!
set_seed(77)

# What size to make latent vector dim?
class VAE_Encoder(nn.Module):
    def __init__(self, image_height, image_width, latent_vector_dim = 32):
        super().__init__()

        # Tighter bottleneck forces the model to compress harder
        # widens the reconstruction gap between normal and anomalous images.

        # CNN network
        self.convolution = nn.Sequential(

            nn.Conv2d(3, 32, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(32),

            nn.Conv2d(32, 64, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(64),

            nn.Conv2d(64, 128, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(128),

            nn.Conv2d(128, 256, 3, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(256),
        )

        # Dummy pass to get flattened_size and spatial_size
        dummy_input = torch.zeros(1, 3, image_height, image_width)
        dummy_output = self.convolution(dummy_input)

        self.flattened_size = dummy_output.view(1, -1).size(1)
        self.spatial_shape = dummy_output.shape[1:]

        self.fully_connected_mu = nn.Linear(self.flattened_size, latent_vector_dim)
        self.fully_connected_log_var = nn.Linear(self.flattened_size, latent_vector_dim)

        # # fully connected layer
        # self.fully_connected_mu = nn.LazyLinear(latent_vector_dim)
        # # fully connected layer
        # self.fully_connnected_log_var = nn.LazyLinear(latent_vector_dim)

    def forward(self,x):

        # Go through our convolutional layers
        z = self.convolution(x)

        # flatten output into latent vector
        # if doing 1x1x1 convolution you do not flatten you jsut march on

        x = torch.flatten(z, start_dim =1)

        # now we want our flattened vector to pass through both fc layers to yeild 2 parameters which will act as our mean and variance
        mu = self.fully_connected_mu(x)
        log_var = self.fully_connected_log_var(x)

        return mu, log_var

def reparametrization(mu, log_var):
      '''
      Here I want to create gaussian noise, select something random from there and do a shift and scale for mu and logvar
      '''
      # std = sqrt(variance)
      var = torch.exp(log_var)
      std = torch.sqrt(var)

      # torch.randn_like returns a tensor with same size as input of a random value from a gaussian distribution with mean 0 and std 1
      # inputting in std as want to have same shapw
      eps = torch.randn_like(std)

      # scale and shift are gaussian by the mu and std
      # z = mean + (random noise * standard deviation)
      z = mu + (eps *std)

      return z

class VAE_Decoder(nn.Module):
    def __init__(self, latent_vector_dim, flattened_size, spatial_shape):
        super().__init__()
        self.spatial_shape = spatial_shape

        self.fully_connected_decoder_in = nn.Linear(latent_vector_dim, flattened_size)

        # decoder mirrors encoder and reverses to reconstruct the spacial resolution
        self.decoder = nn.Sequential(
            nn.Unflatten(1, self.spatial_shape),

            nn.ConvTranspose2d(256, 128, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(128),

            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(64),

            nn.ConvTranspose2d(64, 32, 4, stride=2, padding=1),
            nn.LeakyReLU(0.2),
            nn.BatchNorm2d(32),

            nn.ConvTranspose2d(32, 3, 4, stride=2, padding=1),
            nn.Sigmoid()
        )


    def forward(self, z):

        # expand the latent vector into an input big enough for our decoder
        x = self.fully_connected_decoder_in(z)
        output = self.decoder(x)
        return output

def VAE_loss(x, recon_out, mu, log_var, ssim_metric):

  # Reconstruction loss (SSIM)
  ssim_score = ssim_metric(recon_out, x)

  reconstruction_loss = 1.0 - ssim_score

  #KL loss (ai wrote this for me :) )
  kl_loss = -0.5 * torch.mean(
        1 + log_var - mu.pow(2) - log_var.exp())

  # output L = recon_loss + kl_loss
  return reconstruction_loss + kl_loss

# Full Encoder and Decoder
class VAE(nn.Module):
  def __init__(self, image_height, image_width, latent_vector_dim = 32, num_epochs=30):
    super().__init__()

    self.encoder = VAE_Encoder(image_height, image_width)

    self.decoder = VAE_Decoder(latent_vector_dim, self.encoder.flattened_size, self.encoder.spatial_shape)

  def forward(self, x):
    mu, logvar = self.encoder(x)
    z = reparametrization(mu, logvar)
    reconstructed_output = self.decoder(z)

    return reconstructed_output, mu, logvar

# Made with AI
# Outputs the input images and corresponding reconstructed images
def visualize_reconstructions(model, test_data, num_images=5):
    """Passes a few test images through the model and plots the original vs. reconstruction."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    indices = np.random.choice(len(test_data), num_images, replace=False)
    sample_images = test_data[indices]

    # Convert to PyTorch tensor and fix dimensions for model (N, C, H, W)
    x = torch.tensor(sample_images).permute(0, 3, 1, 2).float().to(device)

    if x.max() > 1.0:
        x = x / 255.0

    with torch.no_grad():
        reconstructed = model(x)[0]

    # Move back to CPU and format for matplotlib (N, H, W, C)
    recon_images = reconstructed.permute(0, 2, 3, 1).cpu().numpy()

    recon_images = np.clip(recon_images, 0.0, 1.0)

    # Plotting
    fig, axes = plt.subplots(num_images, 2, figsize=(6, 2.5 * num_images))
    fig.suptitle("Original vs Reconstructed", fontsize=16)

    for i in range(num_images):
        # Original Image
        axes[i, 0].imshow(orig_img, cmap='gray' if len(orig_img.shape) == 2 else None)
        axes[i, 0].set_title("Original")
        axes[i, 0].axis('off')

        # Reconstructed Image
        axes[i, 1].imshow(recon_img, cmap='gray' if len(recon_img.shape) == 2 else None)
        axes[i, 1].set_title("Reconstructed")
        axes[i, 1].axis('off')

    plt.tight_layout()
    plt.show()

def train_model(model, dataset, num_epochs, learning_rate=0.5e-4):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)

    # SSIM init ((our image values are 0 to 1))
    ssim_metric = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)

    # convert numpy to torch, need to rearrange the dimensions
    x = torch.tensor(dataset).permute(0,3,1,2).float().to(device)

    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    for epoch in range(num_epochs):

      model.train()

      # compute vae forward
      recon_out, mu, logvar = model(x)

      # compute loss
      loss = VAE_loss(x, recon_out, mu, logvar, ssim_metric)

      # clear old gradients from last iter
      optimizer.zero_grad()

      # backward pass for optimization
      loss.backward()

      # update
      optimizer.step()

      print("epoch",epoch,"loss",loss.item())


def predict(model, test_data):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    # Initialize SSIM with reduction='none' to get individual scores per image
    ssim_metric = StructuralSimilarityIndexMeasure(data_range=1.0, reduction='none').to(device)

    x = torch.tensor(test_data).permute(0,3,1,2).float().to(device)

    with torch.no_grad():
        x_hat = model(x)[0]

        # Calculate SSIM for each image
        # (1.0 means perfect match, 0.0 means no match)
        ssim_scores = ssim_metric(x_hat, x)

        # Convert SSIM to an "error" or "anomaly" score (higher = more anomalous)
        errors = 1.0 - ssim_scores

    return errors.cpu().numpy()

def do_analysis(class_name):
  training_images, testing_images, testing_labels = load_dataset(class_name=class_name)

  img_height = training_images.shape[1]
  img_width = training_images.shape[2]

  vae_model = VAE(img_height, img_width)

  train_model(vae_model, training_images, num_epochs=30)

  predictions = predict(vae_model, testing_images)
  basic_evaluation(predictions, testing_labels)
  visualize_reconstructions(vae_model, testing_images, num_images=3)

print("screws analysis")
do_analysis('screws')
print("pasta analysis")
do_analysis('pasta')
print("capsule analysis")
do_analysis('capsule')